<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GradosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('grados')->delete();
        
        \DB::table('grados')->insert(array (
            0 => 
            array (
                'id' => 1,
                'tipo' => 'Kyu',
                'numero' => '10mo.',
                'nombre' => 'Cinturon Blanco',
                'image' => 'grados/May2026/JaZvAnqs6lUsyMWZDUTRday06pm.avif',
                'puntas' => 3,
                'dias' => 90,
                'status' => 1,
                'orden' => NULL,
                'created_at' => '2026-04-23 09:02:59',
                'updated_at' => '2026-05-06 19:44:36',
                'registerUser_id' => NULL,
                'registerRole' => NULL,
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'tipo' => 'Kyu',
                'numero' => '9no.',
                'nombre' => 'Cinturon Blanco Franja Amarilla',
                'image' => 'grados/May2026/fE10LjHgxWGXI1VP7ZRvday06pm.avif',
                'puntas' => 3,
                'dias' => 90,
                'status' => 1,
                'orden' => NULL,
                'created_at' => '2026-04-23 17:28:29',
                'updated_at' => '2026-05-06 19:47:11',
                'registerUser_id' => NULL,
                'registerRole' => NULL,
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'tipo' => 'Kyu',
                'numero' => '8vo.',
                'nombre' => 'Cinturon Amarillo',
                'image' => 'grados/May2026/LIGrx7vQSkaFe8KFQ6HYday06pm.avif',
                'puntas' => 4,
                'dias' => 120,
                'status' => 1,
                'orden' => NULL,
                'created_at' => '2026-04-23 17:29:37',
                'updated_at' => '2026-05-06 19:54:36',
                'registerUser_id' => NULL,
                'registerRole' => NULL,
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'tipo' => 'Kyu',
                'numero' => '7mo.',
                'nombre' => 'Cinturon Naranja',
                'image' => 'grados/May2026/hLHJ3aaHovsE67716KaZday06pm.avif',
                'puntas' => 6,
                'dias' => 180,
                'status' => 1,
                'orden' => NULL,
                'created_at' => '2026-04-23 17:30:20',
                'updated_at' => '2026-05-12 05:52:20',
                'registerUser_id' => NULL,
                'registerRole' => NULL,
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'tipo' => 'Kyu',
                'numero' => '6to',
                'nombre' => 'Cinturon Azul',
                'image' => 'grados/May2026/eR0riPHPyx0ipS0aynr2day06pm.avif',
                'puntas' => 6,
                'dias' => 180,
                'status' => 1,
                'orden' => NULL,
                'created_at' => '2026-04-24 19:00:31',
                'updated_at' => '2026-05-06 19:55:46',
                'registerUser_id' => NULL,
                'registerRole' => NULL,
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'tipo' => 'Kyu',
                'numero' => '5to',
                'nombre' => 'Cinturon Lila',
                'image' => 'grados/May2026/pwC9df5JRsESrXLzWXe5day06pm.avif',
                'puntas' => 6,
                'dias' => 180,
                'status' => 1,
                'orden' => NULL,
                'created_at' => '2026-04-24 19:02:40',
                'updated_at' => '2026-05-06 19:56:08',
                'registerUser_id' => NULL,
                'registerRole' => NULL,
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'tipo' => 'Kyu',
                'numero' => '4to',
                'nombre' => 'Cinturon Verde',
                'image' => 'grados/May2026/Zb6GORoq1Bxp50jgmh9xday06pm.avif',
                'puntas' => 6,
                'dias' => 180,
                'status' => 1,
                'orden' => NULL,
                'created_at' => '2026-04-24 19:21:17',
                'updated_at' => '2026-05-06 19:56:25',
                'registerUser_id' => NULL,
                'registerRole' => NULL,
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'tipo' => 'Kyu',
                'numero' => '3er',
                'nombre' => 'Cinturon Marron Tres Puntas',
                'image' => 'grados/May2026/zAQ48LSgcPGjkAaMU7tZday06pm.avif',
                'puntas' => 3,
                'dias' => 180,
                'status' => 1,
                'orden' => NULL,
                'created_at' => '2026-04-24 19:23:35',
                'updated_at' => '2026-05-06 19:57:32',
                'registerUser_id' => NULL,
                'registerRole' => NULL,
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'tipo' => 'Kyu',
                'numero' => '2do',
                'nombre' => 'Cinturon Marron Dos Puntas',
                'image' => 'grados/May2026/8jOCNYcIYGVKNVNVsq0Mday06pm.avif',
                'puntas' => 3,
                'dias' => 180,
                'status' => 1,
                'orden' => NULL,
                'created_at' => '2026-04-24 19:24:06',
                'updated_at' => '2026-05-12 05:53:13',
                'registerUser_id' => NULL,
                'registerRole' => NULL,
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'tipo' => 'Kyu',
                'numero' => '1er',
                'nombre' => 'Cinturon Marron Una Punta',
                'image' => 'grados/May2026/Cc7MIJEUYE9VKLTr7YPiday06pm.avif',
                'puntas' => 2,
                'dias' => 360,
                'status' => 1,
                'orden' => NULL,
                'created_at' => '2026-04-24 19:24:38',
                'updated_at' => '2026-05-12 05:53:51',
                'registerUser_id' => NULL,
                'registerRole' => NULL,
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'tipo' => 'Dan',
                'numero' => '1er',
                'nombre' => 'Cinturon Negro',
                'image' => 'grados/May2026/AGVTtIvWoMchaUUXjhJbday07am.avif',
                'puntas' => 0,
                'dias' => 720,
                'status' => 1,
                'orden' => NULL,
                'created_at' => '2026-05-06 20:10:12',
                'updated_at' => '2026-05-12 05:54:39',
                'registerUser_id' => 2,
                'registerRole' => 'administrador',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
        ));
        
        
    }
}