<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Inicio',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-house',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2024-10-18 08:31:13',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2026-04-22 13:59:52',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Usuarios',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 1,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2024-10-18 08:33:38',
                'route' => 'voyager.users.index',
                'parameters' => 'null',
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 14,
                'order' => 2,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2026-04-04 14:52:50',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Herramientas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2026-05-05 22:25:08',
                'route' => NULL,
                'parameters' => '',
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2026-04-20 03:34:38',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2026-04-22 13:59:52',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2026-04-22 13:59:52',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2026-04-22 13:59:52',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Configuración',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2024-10-18 06:28:27',
                'updated_at' => '2026-04-23 03:54:34',
                'route' => 'voyager.settings.index',
                'parameters' => 'null',
            ),
            10 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Limpiar cache',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-broom',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2024-12-09 04:33:25',
                'updated_at' => '2026-04-23 03:54:34',
                'route' => 'clear.cache',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Personas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-person',
                'color' => NULL,
                'parent_id' => 40,
                'order' => 1,
                'created_at' => '2025-04-07 01:43:00',
                'updated_at' => '2026-04-23 03:54:54',
                'route' => 'voyager.people.index',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Ciudades',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-city',
                'color' => '#000000',
                'parent_id' => 49,
                'order' => 1,
                'created_at' => '2026-04-04 09:31:06',
                'updated_at' => '2026-04-23 03:54:54',
                'route' => 'voyager.ciudads.index',
                'parameters' => 'null',
            ),
            13 => 
            array (
                'id' => 23,
                'menu_id' => 1,
                'title' => 'Torneos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-trophy',
                'color' => NULL,
                'parent_id' => 32,
                'order' => 1,
                'created_at' => '2026-04-04 09:54:51',
                'updated_at' => '2026-04-08 03:43:14',
                'route' => 'voyager.torneos.index',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'Categorias',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-layer-group',
                'color' => NULL,
                'parent_id' => 32,
                'order' => 3,
                'created_at' => '2026-04-04 15:21:22',
                'updated_at' => '2026-04-22 14:00:01',
                'route' => 'voyager.categorias.index',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 28,
                'menu_id' => 1,
                'title' => 'Grados',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-bezier-curve',
                'color' => NULL,
                'parent_id' => 49,
                'order' => 3,
                'created_at' => '2026-04-04 16:44:14',
                'updated_at' => '2026-04-23 04:59:55',
                'route' => 'voyager.grados.index',
                'parameters' => NULL,
            ),
            16 => 
            array (
                'id' => 29,
                'menu_id' => 1,
                'title' => 'Modalidades',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-brands fa-markdown',
                'color' => NULL,
                'parent_id' => 32,
                'order' => 2,
                'created_at' => '2026-04-04 17:38:51',
                'updated_at' => '2026-04-22 14:00:01',
                'route' => 'voyager.modalidas.index',
                'parameters' => NULL,
            ),
            17 => 
            array (
                'id' => 31,
                'menu_id' => 1,
                'title' => 'Tablero Kumite',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-hand-fist',
                'color' => '#000000',
                'parent_id' => 32,
                'order' => 5,
                'created_at' => '2026-04-05 11:54:13',
                'updated_at' => '2026-04-22 14:00:01',
                'route' => 'kumite.temporizador',
                'parameters' => 'null',
            ),
            18 => 
            array (
                'id' => 32,
                'menu_id' => 1,
                'title' => 'Campeonatos - Eventos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-brands fa-meetup',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2026-04-05 11:54:49',
                'updated_at' => '2026-04-19 13:11:11',
                'route' => NULL,
                'parameters' => '',
            ),
            19 => 
            array (
                'id' => 35,
                'menu_id' => 1,
                'title' => 'Horarios',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-clock',
                'color' => NULL,
                'parent_id' => 49,
                'order' => 4,
                'created_at' => '2026-04-07 10:40:57',
                'updated_at' => '2026-05-05 22:24:28',
                'route' => 'voyager.horarios.index',
                'parameters' => NULL,
            ),
            20 => 
            array (
                'id' => 36,
                'menu_id' => 1,
                'title' => 'Dojos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-archway',
                'color' => NULL,
                'parent_id' => 49,
                'order' => 2,
                'created_at' => '2026-04-08 02:53:17',
                'updated_at' => '2026-04-23 03:54:54',
                'route' => 'voyager.dojos.index',
                'parameters' => NULL,
            ),
            21 => 
            array (
                'id' => 38,
                'menu_id' => 1,
                'title' => 'Alumnos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-user-graduate',
                'color' => NULL,
                'parent_id' => 40,
                'order' => 3,
                'created_at' => '2026-04-08 05:08:26',
                'updated_at' => '2026-05-05 22:24:46',
                'route' => 'voyager.alumnos.index',
                'parameters' => NULL,
            ),
            22 => 
            array (
                'id' => 39,
                'menu_id' => 1,
                'title' => 'Parentescos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-brands fa-pixiv',
                'color' => NULL,
                'parent_id' => 49,
                'order' => 5,
                'created_at' => '2026-04-09 14:33:58',
                'updated_at' => '2026-05-05 22:24:35',
                'route' => 'voyager.parentescos.index',
                'parameters' => NULL,
            ),
            23 => 
            array (
                'id' => 40,
                'menu_id' => 1,
                'title' => 'Administración',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-regular fa-folder-open',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2026-04-19 13:04:22',
                'updated_at' => '2026-05-05 22:24:12',
                'route' => NULL,
                'parameters' => '',
            ),
            24 => 
            array (
                'id' => 44,
                'menu_id' => 1,
                'title' => 'Listado de Katas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-person-falling',
                'color' => '#000000',
                'parent_id' => 32,
                'order' => 4,
                'created_at' => '2026-04-20 03:33:01',
                'updated_at' => '2026-04-22 14:00:01',
                'route' => 'voyager.katas.index',
                'parameters' => 'null',
            ),
            25 => 
            array (
                'id' => 45,
                'menu_id' => 1,
                'title' => 'Tablero Kata',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-chess-board',
                'color' => '#000000',
                'parent_id' => 32,
                'order' => 6,
                'created_at' => '2026-04-20 03:50:43',
                'updated_at' => '2026-04-22 14:00:01',
                'route' => 'tablero.kata',
                'parameters' => NULL,
            ),
            26 => 
            array (
                'id' => 48,
                'menu_id' => 1,
                'title' => 'Usuarios',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2026-04-23 02:50:51',
                'updated_at' => '2026-04-23 03:54:34',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            27 => 
            array (
                'id' => 49,
                'menu_id' => 1,
                'title' => 'Parametros',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-params',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2026-04-23 03:54:29',
                'updated_at' => '2026-04-23 03:54:34',
                'route' => NULL,
                'parameters' => '',
            ),
            28 => 
            array (
                'id' => 50,
                'menu_id' => 1,
                'title' => 'Asistencias',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-clipboard-user',
                'color' => NULL,
                'parent_id' => 40,
                'order' => 2,
                'created_at' => '2026-05-01 13:19:25',
                'updated_at' => '2026-05-05 22:24:44',
                'route' => 'voyager.asistencias.index',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}