<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PeopleTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('people')->delete();
        
        \DB::table('people')->insert(array (
            0 => 
            array (
                'id' => 1,
                'documentType' => 'Ci',
                'dojo_id' => 1,
                'ci' => '3190582',
                'first_name' => 'Walter Landivar Limpias',
                'birth_date' => '1970-01-08',
                'email' => 'wally.landivar@gmail.com',
                'country_code' => '591',
                'phone' => '72841511',
            'address' => 'Urbanizacion Cipriano Barace (Paititi), Avenida Trinidad, nro 39 (3era. Entrada).',
                'gender' => 'Masculino',
                'sangre' => NULL,
                'image' => 'people/May2026/r3T6390y7rnUm8BtYmapday02pm.avif',
                'status' => 1,
                'created_at' => '2026-04-24 11:40:38',
                'updated_at' => '2026-05-02 18:55:50',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'documentType' => 'Ci',
                'dojo_id' => 2,
                'ci' => '10788020',
                'first_name' => 'Jorge Becerra Figueroa',
                'birth_date' => '1998-05-15',
                'email' => 'jorgebecerrafigueroa@gmail.com',
                'country_code' => '591',
                'phone' => '77848840',
                'address' => 'Av. Eucaliptos esq. Marcelo Quiroga, Cochabamba',
                'gender' => 'Masculino',
            'sangre' => 'orh(-)',
                'image' => 'people/May2026/RVMRC1BCvEcwnWhMuybPday02pm.avif',
                'status' => 1,
                'created_at' => '2026-04-24 14:11:45',
                'updated_at' => '2026-05-06 15:42:59',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'documentType' => 'Ci',
                'dojo_id' => 1,
                'ci' => '5615899',
                'first_name' => 'Andrea Nacif Alvarado',
                'birth_date' => '1986-02-15',
                'email' => NULL,
                'country_code' => '591',
                'phone' => '76860405',
                'address' => 'Condominio El Dorado, Trinidad, Beni',
                'gender' => 'Femenino',
                'sangre' => NULL,
                'image' => NULL,
                'status' => 1,
                'created_at' => '2026-04-24 14:13:48',
                'updated_at' => '2026-04-24 14:13:48',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'documentType' => 'Ci',
                'dojo_id' => 1,
                'ci' => '3581477',
                'first_name' => 'Gustavo Adolfo Roca Aukel',
                'birth_date' => '1983-06-23',
                'email' => NULL,
                'country_code' => '591',
                'phone' => '76876303',
                'address' => 'Condominio el Dorado, Trinidad',
                'gender' => 'Masculino',
                'sangre' => NULL,
                'image' => 'people/May2026/62aVlspeuCCmcoTa61usday02pm.avif',
                'status' => 1,
                'created_at' => '2026-04-24 14:19:49',
                'updated_at' => '2026-05-02 18:54:38',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'documentType' => 'Ci',
                'dojo_id' => 5,
                'ci' => '4162842',
                'first_name' => 'Walter Justiniano Vaca',
                'birth_date' => '1978-12-06',
                'email' => NULL,
                'country_code' => '591',
                'phone' => '73900174',
                'address' => 'Calle Julio Céspedes 172, Trinidad',
                'gender' => 'Masculino',
                'sangre' => NULL,
                'image' => 'people/May2026/bW3soOsQGSejtoh9QbHNday02pm.avif',
                'status' => 1,
                'created_at' => '2026-04-24 14:33:21',
                'updated_at' => '2026-05-02 18:54:12',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'documentType' => 'Ci',
                'dojo_id' => 4,
                'ci' => '99999901',
                'first_name' => 'Alfredo Taraune Becerra',
                'birth_date' => NULL,
                'email' => NULL,
                'country_code' => '591',
                'phone' => '75890956',
                'address' => 'Calle Felix Satori nro 658',
                'gender' => 'Masculino',
                'sangre' => NULL,
                'image' => 'people/May2026/rpZdTfpXVnI5RHq0So1gday02pm.avif',
                'status' => 1,
                'created_at' => '2026-04-24 14:36:46',
                'updated_at' => '2026-05-02 18:53:51',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'documentType' => 'Ci',
                'dojo_id' => 3,
                'ci' => '1718817',
                'first_name' => 'Roberto Zabala Atipobo',
                'birth_date' => '1961-10-13',
                'email' => NULL,
                'country_code' => '591',
                'phone' => '71148006',
                'address' => 'Calle Felix Satori nro 658',
                'gender' => 'Masculino',
                'sangre' => NULL,
                'image' => 'people/May2026/9ytuUYRAEXuxAoh6PFxYday02pm.avif',
                'status' => 1,
                'created_at' => '2026-04-24 14:42:20',
                'updated_at' => '2026-05-02 18:53:34',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'documentType' => 'Ci',
                'dojo_id' => 3,
                'ci' => '15144359',
                'first_name' => 'Gustavo Andres Roca Nacif',
                'birth_date' => '1986-01-18',
                'email' => NULL,
                'country_code' => '591',
                'phone' => NULL,
                'address' => 'Condominio el Dorado',
                'gender' => 'Masculino',
                'sangre' => NULL,
                'image' => 'people/May2026/BzQwiGvx6iPAoCdhGy0Dday02pm.avif',
                'status' => 1,
                'created_at' => '2026-04-24 14:45:10',
                'updated_at' => '2026-05-02 18:53:10',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'documentType' => 'Ci',
                'dojo_id' => 3,
                'ci' => '15168046',
                'first_name' => 'Abraham Ribera Ortiz',
                'birth_date' => '2018-01-25',
                'email' => NULL,
                'country_code' => '591',
                'phone' => NULL,
                'address' => 'Avenida Perequije, Condominio Duo, casa nro. 3',
                'gender' => 'Masculino',
                'sangre' => NULL,
                'image' => 'people/May2026/qWAQxUPf8tODcrbAZYoUday02pm.avif',
                'status' => 1,
                'created_at' => '2026-04-24 17:32:56',
                'updated_at' => '2026-05-02 18:52:48',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'documentType' => 'Ci',
                'dojo_id' => 3,
                'ci' => '5599690',
                'first_name' => 'Darwin Ribera Moreno',
                'birth_date' => '1987-08-19',
                'email' => NULL,
                'country_code' => '591',
                'phone' => '75196367',
                'address' => 'Avenida Perequije Condominio Duo, casa nro. 3',
                'gender' => 'Masculino',
                'sangre' => NULL,
                'image' => 'people/May2026/Ai0U19iURFnGkla6UnPGday02pm.avif',
                'status' => 1,
                'created_at' => '2026-04-24 17:57:56',
                'updated_at' => '2026-05-02 18:52:28',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'documentType' => 'Ci',
                'dojo_id' => 3,
                'ci' => '1099813',
                'first_name' => 'Isabel Alejandra Ortiz Barron',
                'birth_date' => '1979-11-30',
                'email' => NULL,
                'country_code' => '591',
                'phone' => '69400060',
                'address' => 'Avenida Perequije, Condominio Duo, Casa nro. 3',
                'gender' => 'Femenino',
                'sangre' => NULL,
                'image' => NULL,
                'status' => 1,
                'created_at' => '2026-04-24 18:00:07',
                'updated_at' => '2026-05-01 17:10:06',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'documentType' => 'Ci',
                'dojo_id' => 3,
                'ci' => '99999902',
                'first_name' => 'Rosario Barron Aramayo',
                'birth_date' => NULL,
                'email' => NULL,
                'country_code' => '591',
                'phone' => '71130652',
                'address' => 'Avenida Vainilla Pasando el canal Guapomo',
                'gender' => 'Femenino',
                'sangre' => NULL,
                'image' => NULL,
                'status' => 1,
                'created_at' => '2026-04-24 18:01:58',
                'updated_at' => '2026-04-24 18:01:58',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'documentType' => 'Ci',
                'dojo_id' => 2,
                'ci' => '15004462',
                'first_name' => 'Oriana Mendoza Barba',
                'birth_date' => '2016-06-24',
                'email' => NULL,
                'country_code' => '591',
                'phone' => NULL,
                'address' => NULL,
                'gender' => 'Femenino',
            'sangre' => 'orh(+)',
                'image' => 'people/May2026/I44kFRvAFCPwkVLlgAwuday06pm.avif',
                'status' => 1,
                'created_at' => '2026-05-06 15:41:43',
                'updated_at' => '2026-05-06 15:41:43',
                'registerUser_id' => 3,
                'registerRole' => 'administrador_dojo',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'documentType' => 'Ci',
                'dojo_id' => 3,
                'ci' => '13891679',
                'first_name' => 'Benjamin Colque Lopez',
                'birth_date' => '2014-04-15',
                'email' => NULL,
                'country_code' => '591',
                'phone' => NULL,
                'address' => 'Calle Jarajorechi Nro. 777, zona Villa Corina.',
                'gender' => 'Masculino',
            'sangre' => 'orh(+)',
                'image' => 'people/May2026/NrvDiTRr8EnZShQpJOHCday12am.avif',
                'status' => 1,
                'created_at' => '2026-05-12 04:55:06',
                'updated_at' => '2026-05-12 04:55:06',
                'registerUser_id' => 4,
                'registerRole' => 'administrador_dojo',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'documentType' => 'Ci',
                'dojo_id' => 6,
                'ci' => '5588395',
                'first_name' => 'Luis Ernesto Zabala Moreno',
                'birth_date' => '2012-01-12',
                'email' => NULL,
                'country_code' => '591',
                'phone' => '72824170',
                'address' => 'Calle Felix Satori nro 658',
                'gender' => 'Masculino',
                'sangre' => NULL,
                'image' => 'people/May2026/j0h6lNV4R82Rh8Quhb0eday12pm.avif',
                'status' => 1,
                'created_at' => '2026-05-12 16:21:01',
                'updated_at' => '2026-05-12 16:21:01',
                'registerUser_id' => 2,
                'registerRole' => 'administrador',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
        ));
        
        
    }
}